name: flutter_system_proxy
description: A Flutter plugin to detect system proxy settings, helping non-proxy-aware HTTP clients retrieve proxy configurations for successful network requests.
version: 0.2.1
homepage: https://github.com/BrowserStackCE/flutter_system_proxy.git

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.browserstack.fluttersystemproxy.flutter_system_proxy
        pluginClass: FlutterSystemProxyPlugin
      ios:
        pluginClass: FlutterSystemProxyPlugin